FROM ghcr.io/deck-app/nginx:v7.4
LABEL maintainer Naba Das <hello@get-deck.com>

# Persistent runtime dependencies
# Example RUN apk add --no-cache php7-openssl php7-sysvmsg php7-curl

RUN mkdir -p /app
RUN mkdir -p /var/preview
COPY default.conf /etc/nginx/conf.d/default.conf
COPY default.conf /app/default.conf
RUN wget -O /app/annotations.yaml https://raw.githubusercontent.com/deck-app/stack-preview-screen/main/symfony/annotations.yaml
RUN wget -O /app/defaultController.php https://raw.githubusercontent.com/deck-app/stack-preview-screen/main/symfony/defaultController.php
RUN wget -O /var/preview/index.html https://raw.githubusercontent.com/deck-app/stack-preview-screen/main/symfony/index.html
RUN sed -i "s#{SERVER_ROOT}#/var/preview#g" /etc/nginx/conf.d/default.conf
RUN sed -i "s#{SERVER_ROOT}#/var/www/public#g" /app/default.conf
RUN apk add --no-cache zip git 
RUN apk add php7-pdo php7-zip php7-pdo_mysql php7-intl


WORKDIR /var/www
#PHP display error enable or disable
ARG PHP_VERSION
COPY php_ini/php.ini /etc/php7/php.ini
ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php7/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php7/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk add php7-pecl-xdebug \
&& echo "zend_extension=xdebug" >> /etc/php7/php.ini \
;fi

COPY docker-entrypoint.sh /docker-entrypoint.sh

#SYMFONY_INSTALL enable or disable
ARG SYMFONY_INSTALL
RUN if [ ${SYMFONY_INSTALL} = true ]; then \
sed -i "s#{SYMFONY_INSTALL}#true#g" /docker-entrypoint.sh \
;else \
sed -i "s#{SYMFONY_INSTALL}#false#g" /docker-entrypoint.sh \
;fi

RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony
RUN git config --global user.email "hello@get-deck.com" \ 
    && git config --global user.name "Deck App"

RUN chmod +x /docker-entrypoint.sh
CMD /docker-entrypoint.sh & /sbin/runit-wrapper