FROM ghcr.io/deck-app/apache:v7.4
LABEL maintainer Naba Das <hello@get-deck.com>

# Persistent runtime dependencies
# Example RUN apk add --no-cache php7-openssl php7-sysvmsg php7-curl


RUN mkdir -p /app
RUN mkdir -p /var/preview
COPY httpd.conf /etc/apache2/httpd.conf
COPY httpd.conf /app/httpd.conf
RUN wget -O /var/preview/index.html https://raw.githubusercontent.com/deck-app/stack-preview-screen/main/symfony/index.html
RUN sed -i "s#{SERVER_ROOT}#/var/preview#g" /etc/apache2/httpd.conf
RUN sed -i "s#{SERVER_ROOT}#/var/www/public#g" /app/httpd.conf

WORKDIR /var/www
ARG PHP_VERSION
COPY php.ini /etc/php7/php.ini

ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php7/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php7/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk add php7-pecl-xdebug \
&& echo "zend_extension=xdebug" >> /etc/php7/php.ini \
;fi

RUN apk add php7-pdo php7-zip php7-pdo_mysql php7-intl
RUN apk add zip git

COPY docker-entrypoint.sh /docker-entrypoint.sh

## Linux permission issue
ARG USER_ID
ARG GROUP_ID
RUN apk --no-cache add shadow sudo
RUN ln -s /usr/bin/php /usr/bin/php7
RUN usermod -u ${USER_ID} apache && groupmod -g ${GROUP_ID} apache

# sudo command without password
RUN echo "apache ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers 
RUN composer config --global process-timeout 6000

RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony5/bin/symfony /usr/local/bin/symfony
RUN git config --global user.email "hello@get-deck.com" \ 
    && git config --global user.name "Deck App"

RUN chmod +x /docker-entrypoint.sh
RUN sed -i "s#{PHP_VERSION}#${PHP_VERSION}#g" /docker-entrypoint.sh
## apache2 permission issue
RUN usermod --home /home apache
RUN touch /env
RUN chown -R apache:apache /env
RUN chown -R apache:apache /home
RUN chown -R apache:apache /var/preview/
RUN chown -R apache:apache /usr/sbin/httpd
RUN chown -R apache:apache /etc/service/apache
RUN chown -R apache:apache /sbin/
RUN chown -R apache:apache /etc/service/
RUN chown -R apache:apache /etc/apache2
RUN chown -R apache:apache /var/run/apache2
RUN chown -R apache:apache /var/log/apache2
USER apache
CMD /docker-entrypoint.sh & /sbin/runit-wrapper